"""Initial schema from models

Revision ID: 352cafa6cd86
Revises:
Create Date: 2025-11-08 17:03:46.331074

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "352cafa6cd86"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_consignment_stock_customer", table_name="consignment_stock")
    op.drop_index("idx_consignment_stock_product", table_name="consignment_stock")
    op.drop_index("customers_email_unique", table_name="customers", postgresql_where="(email IS NOT NULL)")
    op.create_unique_constraint(None, "customers", ["email"])
    op.drop_index("idx_delivery_note_items_dn", table_name="delivery_note_items")
    op.drop_index("idx_delivery_note_items_product", table_name="delivery_note_items")
    op.drop_constraint("delivery_notes_delivery_note_number_key", "delivery_notes", type_="unique")
    op.drop_index("idx_delivery_notes_customer", table_name="delivery_notes")
    op.drop_index("idx_delivery_notes_date", table_name="delivery_notes")
    op.drop_index("idx_delivery_notes_number", table_name="delivery_notes")
    op.create_index(
        op.f("ix_delivery_notes_delivery_note_number"), "delivery_notes", ["delivery_note_number"], unique=True
    )
    op.drop_index("idx_invoice_pdf_archive_invoice_id", table_name="invoice_pdf_archive")
    op.drop_index("idx_invoice_pdf_archive_pdf_hash", table_name="invoice_pdf_archive")
    op.drop_constraint("unique_invoice_pdf", "invoice_pdf_archive", type_="unique")
    op.drop_constraint("invoice_pdf_archive_invoice_id_fkey", "invoice_pdf_archive", type_="foreignkey")
    op.drop_index("idx_invoice_status_log_changed_at", table_name="invoice_status_log")
    op.drop_index("idx_invoice_status_log_invoice_id", table_name="invoice_status_log")
    op.drop_constraint("invoice_status_log_invoice_id_fkey", "invoice_status_log", type_="foreignkey")
    op.drop_index("idx_payment_checks_invoice_number", table_name="payment_checks")
    op.drop_index("idx_payment_checks_resolved", table_name="payment_checks")
    op.drop_index("idx_payment_checks_status", table_name="payment_checks")
    op.create_index(op.f("ix_payment_checks_invoice_number"), "payment_checks", ["invoice_number"], unique=False)
    op.create_index(op.f("ix_payment_checks_status"), "payment_checks", ["status"], unique=False)
    op.alter_column(
        "reminders",
        "reminder_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_index("idx_reminders_invoice_id", table_name="reminders")
    op.drop_index("idx_reminders_reminder_level", table_name="reminders")
    op.alter_column(
        "stock_adjustments",
        "adjustment_type",
        existing_type=postgresql.ENUM(
            "eigenentnahme",
            "geschenk",
            "verderb",
            "bruch",
            "inventur_plus",
            "inventur_minus",
            "korrektur",
            "sonstiges",
            name="adjustment_type_enum",
        ),
        type_=sa.Enum(
            "eigenentnahme",
            "geschenk",
            "verderb",
            "bruch",
            "inventur_plus",
            "inventur_minus",
            "korrektur",
            "sonstiges",
            name="adjustment_type_enum",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.drop_index("idx_stock_adjustments_adjusted_at", table_name="stock_adjustments")
    op.drop_index("idx_stock_adjustments_adjusted_by", table_name="stock_adjustments")
    op.drop_index("idx_stock_adjustments_product_id", table_name="stock_adjustments")
    op.drop_constraint("stock_adjustments_adjusted_by_fkey", "stock_adjustments", type_="foreignkey")
    op.drop_constraint("stock_adjustments_product_id_fkey", "stock_adjustments", type_="foreignkey")
    op.create_foreign_key(None, "stock_adjustments", "users", ["adjusted_by"], ["id"])
    op.create_foreign_key(None, "stock_adjustments", "products", ["product_id"], ["id"])
    op.alter_column(
        "users",
        "reseller_type",
        existing_type=postgresql.ENUM(
            "none",
            "type1_ust_extern",
            "type2_non_ust_extern",
            "type3_non_ust_pwa",
            "type4_owner_market",
            name="reseller_type_enum",
        ),
        type_=sa.Enum(
            "none",
            "type1_ust_extern",
            "type2_non_ust_extern",
            "type3_non_ust_pwa",
            "type4_owner_market",
            name="reseller_type_enum",
            native_enum=False,
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'none'::reseller_type_enum"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "reseller_type",
        existing_type=sa.Enum(
            "none",
            "type1_ust_extern",
            "type2_non_ust_extern",
            "type3_non_ust_pwa",
            "type4_owner_market",
            name="reseller_type_enum",
            native_enum=False,
        ),
        type_=postgresql.ENUM(
            "none",
            "type1_ust_extern",
            "type2_non_ust_extern",
            "type3_non_ust_pwa",
            "type4_owner_market",
            name="reseller_type_enum",
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'none'::reseller_type_enum"),
    )
    op.drop_constraint(None, "stock_adjustments", type_="foreignkey")
    op.drop_constraint(None, "stock_adjustments", type_="foreignkey")
    op.create_foreign_key(
        "stock_adjustments_product_id_fkey",
        "stock_adjustments",
        "products",
        ["product_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "stock_adjustments_adjusted_by_fkey", "stock_adjustments", "users", ["adjusted_by"], ["id"], ondelete="RESTRICT"
    )
    op.create_index("idx_stock_adjustments_product_id", "stock_adjustments", ["product_id"], unique=False)
    op.create_index("idx_stock_adjustments_adjusted_by", "stock_adjustments", ["adjusted_by"], unique=False)
    op.create_index("idx_stock_adjustments_adjusted_at", "stock_adjustments", ["adjusted_at"], unique=False)
    op.alter_column(
        "stock_adjustments",
        "adjustment_type",
        existing_type=sa.Enum(
            "eigenentnahme",
            "geschenk",
            "verderb",
            "bruch",
            "inventur_plus",
            "inventur_minus",
            "korrektur",
            "sonstiges",
            name="adjustment_type_enum",
            native_enum=False,
        ),
        type_=postgresql.ENUM(
            "eigenentnahme",
            "geschenk",
            "verderb",
            "bruch",
            "inventur_plus",
            "inventur_minus",
            "korrektur",
            "sonstiges",
            name="adjustment_type_enum",
        ),
        existing_nullable=False,
    )
    op.create_index("idx_reminders_reminder_level", "reminders", ["reminder_level"], unique=False)
    op.create_index("idx_reminders_invoice_id", "reminders", ["invoice_id"], unique=False)
    op.alter_column(
        "reminders",
        "reminder_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_index(op.f("ix_payment_checks_status"), table_name="payment_checks")
    op.drop_index(op.f("ix_payment_checks_invoice_number"), table_name="payment_checks")
    op.create_index("idx_payment_checks_status", "payment_checks", ["status"], unique=False)
    op.create_index("idx_payment_checks_resolved", "payment_checks", ["resolved"], unique=False)
    op.create_index("idx_payment_checks_invoice_number", "payment_checks", ["invoice_number"], unique=False)
    op.create_foreign_key(
        "invoice_status_log_invoice_id_fkey",
        "invoice_status_log",
        "invoices",
        ["invoice_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index("idx_invoice_status_log_invoice_id", "invoice_status_log", ["invoice_id"], unique=False)
    op.create_index("idx_invoice_status_log_changed_at", "invoice_status_log", ["changed_at"], unique=False)
    op.create_foreign_key(
        "invoice_pdf_archive_invoice_id_fkey",
        "invoice_pdf_archive",
        "invoices",
        ["invoice_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        "unique_invoice_pdf", "invoice_pdf_archive", ["invoice_id", "pdf_filename"], postgresql_nulls_not_distinct=False
    )
    op.create_index("idx_invoice_pdf_archive_pdf_hash", "invoice_pdf_archive", ["pdf_hash"], unique=False)
    op.create_index("idx_invoice_pdf_archive_invoice_id", "invoice_pdf_archive", ["invoice_id"], unique=False)
    op.drop_index(op.f("ix_delivery_notes_delivery_note_number"), table_name="delivery_notes")
    op.create_index("idx_delivery_notes_number", "delivery_notes", ["delivery_note_number"], unique=False)
    op.create_index("idx_delivery_notes_date", "delivery_notes", ["delivery_date"], unique=False)
    op.create_index("idx_delivery_notes_customer", "delivery_notes", ["customer_id"], unique=False)
    op.create_unique_constraint(
        "delivery_notes_delivery_note_number_key",
        "delivery_notes",
        ["delivery_note_number"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index("idx_delivery_note_items_product", "delivery_note_items", ["product_id"], unique=False)
    op.create_index("idx_delivery_note_items_dn", "delivery_note_items", ["delivery_note_id"], unique=False)
    op.drop_constraint(None, "customers", type_="unique")
    op.create_index(
        "customers_email_unique", "customers", ["email"], unique=False, postgresql_where="(email IS NOT NULL)"
    )
    op.create_index("idx_consignment_stock_product", "consignment_stock", ["product_id"], unique=False)
    op.create_index("idx_consignment_stock_customer", "consignment_stock", ["customer_id"], unique=False)
    # ### end Alembic commands ###
