"""Honig-Rueckverfolgbarkeit: Eimer, Charge, Abfuellung

Revision ID: 7913dcf058d0
Revises: 352cafa6cd86
Create Date: 2026-09-05 04:03:43.162972

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7913dcf058d0"
down_revision: Union[str, None] = "352cafa6cd86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "abfuell_chargen",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chargennummer", sa.String(length=50), nullable=False),
        sa.Column("mindesthaltbarkeitsdatum", sa.Date(), nullable=False),
        sa.Column("sorte", sa.String(length=100), nullable=False),
        sa.Column("abfuelldatum", sa.Date(), nullable=False),
        sa.Column("notizen", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_abfuell_chargen_chargennummer"), "abfuell_chargen", ["chargennummer"], unique=True)
    op.create_table(
        "honig_eimer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("eimer_nummer", sa.String(length=20), nullable=False),
        sa.Column("kapazitaet_kg", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("aktiv", sa.Boolean(), nullable=True),
        sa.Column("notizen", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_honig_eimer_eimer_nummer"), "honig_eimer", ["eimer_nummer"], unique=True)
    op.create_table(
        "abfuell_ergebnisse",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("abfuell_charge_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("anzahl_glaeser", sa.Integer(), nullable=False),
        sa.Column("anzahl_glaeser_aktuell", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["abfuell_charge_id"],
            ["abfuell_chargen.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "honig_chargen",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("eimer_id", sa.Integer(), nullable=False),
        sa.Column("sorte", sa.String(length=100), nullable=False),
        sa.Column("schleudertag", sa.Date(), nullable=False),
        sa.Column("gewicht_kg", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("restmenge_kg", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("notizen", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["eimer_id"],
            ["honig_eimer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "abfuellung_quellen",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("abfuell_charge_id", sa.Integer(), nullable=False),
        sa.Column("honig_charge_id", sa.Integer(), nullable=False),
        sa.Column("entnommene_menge_kg", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.ForeignKeyConstraint(
            ["abfuell_charge_id"],
            ["abfuell_chargen.id"],
        ),
        sa.ForeignKeyConstraint(
            ["honig_charge_id"],
            ["honig_chargen.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("abfuellung_quellen")
    op.drop_table("honig_chargen")
    op.drop_table("abfuell_ergebnisse")
    op.drop_index(op.f("ix_honig_eimer_eimer_nummer"), table_name="honig_eimer")
    op.drop_table("honig_eimer")
    op.drop_index(op.f("ix_abfuell_chargen_chargennummer"), table_name="abfuell_chargen")
    op.drop_table("abfuell_chargen")
    # ### end Alembic commands ###
