"""Geraete-Tokens: mehrere pro User, api_token-Feld entfernt

Revision ID: b4134be103fd
Revises: d0d304c713f2
Create Date: 2026-09-05 13:09:23.639370

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4134be103fd"
down_revision: Union[str, None] = "d0d304c713f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_ip", sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_device_tokens_token"), "device_tokens", ["token"], unique=True)
    op.drop_index("api_token", table_name="users")
    op.drop_column("users", "api_token")
    op.drop_column("users", "api_token_expires")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("api_token_expires", mysql.DATETIME(), nullable=True))
    op.add_column("users", sa.Column("api_token", mysql.VARCHAR(length=255), nullable=True))
    op.create_index("api_token", "users", ["api_token"], unique=False)
    op.drop_index(op.f("ix_device_tokens_token"), table_name="device_tokens")
    op.drop_table("device_tokens")
    # ### end Alembic commands ###
