"""HonigCharge: Wassergehalt-Prozent-Feld ergaenzen

Revision ID: d0d304c713f2
Revises: 7913dcf058d0
Create Date: 2026-09-05 11:04:37.102015

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0d304c713f2"
down_revision: Union[str, None] = "7913dcf058d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("honig_chargen", sa.Column("wassergehalt_prozent", sa.Numeric(precision=4, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("honig_chargen", "wassergehalt_prozent")
    # ### end Alembic commands ###
